(() => {
  'use strict';
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const WA='919810958069';
  const money=n=>Number.isFinite(Number(n))&&Number(n)>0?new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(Number(n)):'Price on request';
  const esc=s=>String(s??'').replace(/[&<>"]/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':'&quot;'}[m]));
  const getJSON=async(url,opts={})=>{const r=await fetch(url,{headers:{'Content-Type':'application/json',...(opts.headers||{})},...opts});let j={};try{j=await r.json()}catch{}if(!r.ok)throw new Error(j.error||`Request failed (${r.status})`);return j};
  async function packages(params=''){
    try{return (await getJSON('/api/packages'+params)).packages||[]}catch{
      const all=await fetch('/data/packages.json').then(r=>r.json()); const q=new URLSearchParams(params.replace(/^\?/,'')); let list=all.filter(x=>x.published!==false);
      const term=(q.get('q')||q.get('destination')||'').toLowerCase(), region=(q.get('region')||'').toLowerCase(), type=(q.get('type')||'').toLowerCase(), budget=q.get('budget')||'';
      if(term)list=list.filter(p=>[p.title,p.destination,p.region,p.country,p.summary,...(p.tags||[])].join(' ').toLowerCase().includes(term));
      if(region)list=list.filter(p=>String(p.region).toLowerCase()===region);
      if(type)list=list.filter(p=>String(p.type).toLowerCase()===type||(p.tags||[]).some(t=>String(t).toLowerCase()===type));
      if(budget&&budget!=='Any budget')list=list.filter(p=>{const n=Number(p.startingPrice);if(!n)return false;if(budget==='Under ₹50,000')return n<50000;if(budget==='₹50,000–₹1,00,000')return n>=50000&&n<=100000;if(budget==='₹1,00,000+')return n>100000;return true}); return list;
    }
  }
  const state={lastFocus:null,selectedMood:'Couple'};
  function setupHeader(){
    const header=$('.site-header'); if(header){ addEventListener('scroll',()=>header.classList.toggle('scrolled',scrollY>18),{passive:true}); }
    const menu=$('#menuButton'), mobile=$('#mobileNav'); menu?.addEventListener('click',()=>{const o=mobile.classList.toggle('open');menu.setAttribute('aria-expanded',String(o));menu.textContent=o?'×':'☰'}); $$('#mobileNav a').forEach(a=>a.addEventListener('click',()=>{mobile?.classList.remove('open');if(menu){menu.setAttribute('aria-expanded','false');menu.textContent='☰'}}));
    $$('.nav-item.has-menu').forEach(item=>{const btn=$('button',item), menuEl=$('.nav-menu',item); btn?.addEventListener('click',()=>{const open=item.classList.toggle('open');btn.setAttribute('aria-expanded',String(open)); $$('.nav-item.has-menu').filter(x=>x!==item).forEach(x=>x.classList.remove('open'));}); item.addEventListener('mouseleave',()=>item.classList.remove('open'));});
    document.addEventListener('click',e=>{if(!e.target.closest('.nav-item.has-menu'))$$('.nav-item.has-menu').forEach(x=>x.classList.remove('open'))});
  }
  function focusables(modal){return $$('button,[href],input,select,textarea,[tabindex]:not([tabindex="-1"])',modal).filter(x=>!x.disabled&&x.offsetParent!==null)}
  function openModal(modal,opts={}){if(!modal)return;state.lastFocus=document.activeElement;modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.classList.add('modal-open'); if(opts.destination)$('#tripDestination',modal).value=opts.destination;if(opts.month)$('#tripMonth',modal).value=opts.month==='Any month'?'':opts.month;if(opts.travelers)$('#tripTravellers',modal).value=opts.travelers;if(opts.budget)$('#tripBudget',modal).value=opts.budget;if(opts.mood){const map={solo:'Holiday',couple:'Honeymoon / Romance',family:'Family',adventure:'Adventure',romance:'Honeymoon / Romance',nature:'Nature',custom:'Custom trip','Couple':'Honeymoon / Romance'};const m=map[opts.mood]||opts.mood;const sel=$('#tripMood',modal);if([...sel.options].some(o=>o.value===m))sel.value=m;}setTimeout(()=>focusables(modal)[0]?.focus(),20)}
  function closeModal(modal){if(!modal)return;modal.classList.remove('open');modal.setAttribute('aria-hidden','true');if(!$('.modal.open'))document.body.classList.remove('modal-open');state.lastFocus?.focus?.()}
  function setupModal(){const modal=$('#plannerModal'); $$('.js-plan').forEach(b=>b.addEventListener('click',()=>openModal(modal,{mood:state.selectedMood}))); $$('[data-close-modal]').forEach(b=>b.addEventListener('click',()=>closeModal(modal))); document.addEventListener('keydown',e=>{if(e.key==='Escape'&&modal?.classList.contains('open'))closeModal(modal);if(e.key==='Tab'&&modal?.classList.contains('open')){const f=focusables(modal);if(!f.length)return;const first=f[0],last=f.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}});
    $('#tripForm')?.addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget,status=$('#tripStatus'),button=$('button[type=submit]',form); const fd=new FormData(form);const data=Object.fromEntries(fd.entries()); if(data.website)return; button.disabled=true;status.textContent='Saving your trip request…';try{const j=await getJSON('/api/enquiries',{method:'POST',body:JSON.stringify({...data,source:location.pathname})});status.textContent=`Request saved: ${j.leadId}. Opening WhatsApp…`;setTimeout(()=>window.open(j.whatsappUrl,'_blank','noopener,noreferrer'),250)}catch(err){status.textContent='Lead server is unavailable, so we are continuing on WhatsApp. Please send the pre-filled message to complete your enquiry.';const msg=`Hi MyTravel4Sure, I want to plan a trip.\nName: ${data.name||''}\nPhone: ${data.phone||''}\nDestination: ${data.destination||'Open to suggestions'}\nTravel month: ${data.month||'Flexible'}\nTravellers: ${data.travellers||'Not specified'}\nTrip type: ${data.tripType||'Holiday'}\nBudget: ${data.budget||'Flexible'}`;window.open(`https://wa.me/${WA}?text=${encodeURIComponent(msg)}`,'_blank','noopener,noreferrer')}finally{button.disabled=false}});
  }
  function setupNewsletter(){ $$('.newsletter').forEach(form=>form.addEventListener('submit',async e=>{e.preventDefault();const input=$('input[type=email]',form),status=$('[role=status]',form),button=$('button',form);button.disabled=true;status.textContent='Subscribing…';try{await getJSON('/api/newsletter',{method:'POST',body:JSON.stringify({email:input.value,source:location.pathname,website:''})});status.textContent='Subscribed successfully.';input.value=''}catch(err){status.textContent=err.message}finally{button.disabled=false}})); }
  function setupReveal(){const els=$$('.reveal');if(!('IntersectionObserver'in window)){els.forEach(x=>x.classList.add('is-visible'));return}const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-visible');io.unobserve(e.target)}}),{threshold:.1});els.forEach(x=>x.classList.contains('is-visible')||io.observe(x));if(!matchMedia('(prefers-reduced-motion: reduce)').matches){let t=false;addEventListener('scroll',()=>{if(t)return;t=true;requestAnimationFrame(()=>{document.documentElement.style.setProperty('--hero-shift',`${Math.min(scrollY*.07,26)}px`);t=false})},{passive:true})}}
  function setupHome(){
    $('#holidaySearch')?.addEventListener('submit',e=>{e.preventDefault();const q=new URLSearchParams({destination:$('#destination').value.trim(),month:$('#month').value,travelers:$('#travelers').value,budget:$('#budget').value});location.href='holidays.html?'+q.toString()});
    $('#openSearch')?.addEventListener('click',()=>{scrollTo({top:0,behavior:'smooth'});setTimeout(()=>$('#destination')?.focus(),350)});
    $$('.js-destination').forEach(el=>el.addEventListener('click',e=>{if(el.tagName==='A')return;location.href=`holidays.html?destination=${encodeURIComponent(el.dataset.destination||'')}`}));
    $$('#builderOptions .builder-option').forEach(btn=>btn.addEventListener('click',()=>{$$('#builderOptions .builder-option').forEach(x=>x.classList.remove('selected'));btn.classList.add('selected');state.selectedMood=btn.dataset.mood||'Holiday'}));
    $('#builderGo')?.addEventListener('click',()=>openModal($('#plannerModal'),{mood:state.selectedMood}));
  }
  function packageCard(p){return `<article class="package-card reveal"><a class="package-image" href="package.html?slug=${encodeURIComponent(p.slug)}"><img src="${esc(p.image)}" alt="${esc(p.destination)} holiday" loading="lazy" width="640" height="420"><span>${esc(p.region)}</span></a><div class="package-card-body"><div class="package-meta">${esc(p.nights)}N / ${esc(p.days)}D · ${esc(p.availability)}</div><h3><a href="package.html?slug=${encodeURIComponent(p.slug)}">${esc(p.title)}</a></h3><p>${esc(p.summary)}</p><div class="tag-row">${(p.tags||[]).slice(0,4).map(t=>`<span>${esc(t)}</span>`).join('')}</div><div class="package-card-foot"><div><small>${p.startingPrice?'Starting from':'Quote'}</small><strong>${money(p.startingPrice)}</strong>${p.priceStatus==='reference'?'<em>Reference price — confirm before booking</em>':''}</div><a class="round-arrow" href="package.html?slug=${encodeURIComponent(p.slug)}" aria-label="View package">→</a></div></div></article>`}
  async function setupPackagesPage(){const grid=$('#packageGrid');if(!grid)return;const form=$('#packageFilters');const qs=new URLSearchParams(location.search);['destination','region','type','budget','month','travelers'].forEach(k=>{const el=$(`[name=${k}]`,form);if(el&&qs.get(k))el.value=qs.get(k)});async function render(){const params=new URLSearchParams(new FormData(form));history.replaceState({},'',location.pathname+'?'+params.toString());grid.innerHTML='<div class="loading-state">Finding matching holidays…</div>';try{const list=await packages('?'+params.toString());$('#resultCount').textContent=`${list.length} holiday${list.length===1?'':'s'} found`;grid.innerHTML=list.length?list.map(packageCard).join(''):'<div class="empty-state"><h3>No exact match yet.</h3><p>Try a broader filter or ask us to build a custom holiday.</p><button class="btn btn-orange js-plan" type="button">Build a Custom Trip →</button></div>';setupReveal();$$('.js-plan',grid).forEach(b=>b.addEventListener('click',()=>openModal($('#plannerModal'),{destination:$('[name=destination]',form)?.value,mood:$('[name=type]',form)?.value||'Custom trip'})))}catch(err){grid.innerHTML=`<div class="empty-state"><h3>Could not load packages.</h3><p>${esc(err.message)}</p></div>`}}form.addEventListener('submit',e=>{e.preventDefault();render()});$('#resetFilters')?.addEventListener('click',()=>{form.reset();render()});render()}
  async function setupPackageDetail(){const host=$('#packageDetail');if(!host)return;const slug=new URLSearchParams(location.search).get('slug')||'kashmir-6-days';let p;try{p=(await getJSON('/api/packages/'+encodeURIComponent(slug))).package}catch{const all=await fetch('/data/packages.json').then(r=>r.json());p=all.find(x=>x.slug===slug)}if(!p){host.innerHTML='<div class="empty-state"><h1>Package not found</h1><a class="btn btn-cyan" href="holidays.html">Browse Holidays</a></div>';return}document.title=`${p.title} | MyTravel4Sure`;host.innerHTML=`<section class="package-hero-detail"><img src="${esc(p.image)}" alt="${esc(p.destination)}"><div class="page-hero-shade"></div><div class="container"><span class="eyebrow">${esc(p.region)} · ${p.nights} NIGHTS · ${p.days} DAYS</span><h1>${esc(p.title)}</h1><p>${esc(p.summary)}</p></div></section><section class="page-main"><div class="container package-detail"><div><div class="brand-dots"><span></span><span></span><span></span><span></span><span></span><span></span></div><h2>Your journey, clearly planned.</h2><p class="lead-copy">This is an enquiry-led package. Live hotel inventory, transport availability and the final payable quote are confirmed before booking.</p><div class="detail-block"><h3>Highlights</h3><div class="tag-row large">${(p.highlights||[]).map(x=>`<span>${esc(x)}</span>`).join('')}</div></div><div class="detail-block"><h3>Itinerary</h3><div class="timeline">${(p.itinerary||[]).map((x,i)=>`<div><span>${String(i+1).padStart(2,'0')}</span><section><small>DAY ${i+1}</small><h3>${esc(x)}</h3></section></div>`).join('')}</div></div><div class="detail-block"><h3>Planning inclusions</h3><ul class="clean-list">${(p.inclusions||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div></div><aside class="booking-panel"><span class="eyebrow">CURRENT QUOTE</span><h3>${money(p.startingPrice)}</h3><p>${p.startingPrice?'Starting/reference price shown for this package.':'Price is prepared after dates, traveller count and preferences are confirmed.'}</p><p><b>Availability:</b> ${esc(p.availability)}</p><button class="btn btn-orange btn-wide js-plan" data-destination="${esc(p.destination)}" type="button">Check Availability →</button><small>No payment is collected on this page. Final itinerary and price are confirmed before booking.</small></aside></div></section>`;$$('.js-plan',host).forEach(b=>b.addEventListener('click',()=>openModal($('#plannerModal'),{destination:p.destination,mood:p.type||'Holiday'})))}
  function setupContact(){const form=$('#contactForm');if(!form)return;form.addEventListener('submit',async e=>{e.preventDefault();const status=$('#contactStatus'),button=$('button[type=submit]',form),data=Object.fromEntries(new FormData(form));button.disabled=true;status.textContent='Sending…';try{const j=await getJSON('/api/enquiries',{method:'POST',body:JSON.stringify({...data,tripType:'Contact enquiry',source:'contact-page'})});status.textContent=`Enquiry saved: ${j.leadId}.`;form.reset()}catch(err){status.textContent=err.message}finally{button.disabled=false}})}
  function setupAdmin(){const root=$('#adminApp');if(!root)return;const login=$('#adminLogin'),dash=$('#adminDashboard'),msg=$('#adminMessage');const api=(url,o={})=>getJSON(url,o);async function load(){try{const [leads,subs,pkgs]=await Promise.all([api('/api/admin/leads'),api('/api/admin/newsletter'),api('/api/admin/packages')]);login.hidden=true;dash.hidden=false;$('#leadCount').textContent=leads.leads.length;$('#subscriberCount').textContent=subs.subscribers.length;$('#packageCount').textContent=pkgs.packages.length;$('#leadRows').innerHTML=leads.leads.map(l=>`<tr><td><b>${esc(l.id)}</b><small>${new Date(l.created_at).toLocaleString()}</small></td><td>${esc(l.name)}<small>${esc(l.phone)} ${l.email?`· ${esc(l.email)}`:''}</small></td><td>${esc(l.destination||'Open')}<small>${esc(l.travel_month||'Flexible')} · ${esc(l.travellers||'—')}</small></td><td><select data-lead="${esc(l.id)}">${['new','contacted','qualified','quoted','booked','closed'].map(s=>`<option ${s===l.status?'selected':''}>${s}</option>`).join('')}</select></td></tr>`).join('');$$('[data-lead]').forEach(s=>s.addEventListener('change',()=>api('/api/admin/leads/'+encodeURIComponent(s.dataset.lead),{method:'PATCH',body:JSON.stringify({status:s.value})}).catch(e=>alert(e.message))));$('#packageRows').innerHTML=pkgs.packages.map(p=>`<tr><td>${esc(p.title)}<small>${esc(p.slug)}</small></td><td>${esc(p.destination)}</td><td><input type="number" min="0" data-price="${esc(p.slug)}" value="${p.startingPrice??''}" placeholder="On request"></td><td><input type="checkbox" data-pub="${esc(p.slug)}" ${p.published?'checked':''}></td><td><button class="mini-btn" data-save="${esc(p.slug)}">Save</button></td></tr>`).join('');$$('[data-save]').forEach(b=>b.addEventListener('click',async()=>{const slug=b.dataset.save,price=$(`[data-price="${CSS.escape(slug)}"]`).value,published=$(`[data-pub="${CSS.escape(slug)}"]`).checked;b.disabled=true;try{await api('/api/admin/packages/'+encodeURIComponent(slug),{method:'PATCH',body:JSON.stringify({startingPrice:price===''?null:Number(price),published})});b.textContent='Saved'}catch(e){alert(e.message)}finally{setTimeout(()=>{b.disabled=false;b.textContent='Save'},700)}}));$('#subscriberRows').innerHTML=subs.subscribers.map(s=>`<tr><td>${esc(s.email)}</td><td>${new Date(s.created_at).toLocaleString()}</td><td>${esc(s.source||'')}</td></tr>`).join('')}catch{login.hidden=false;dash.hidden=true}}
    login.addEventListener('submit',async e=>{e.preventDefault();msg.textContent='Signing in…';try{await api('/api/admin/login',{method:'POST',body:JSON.stringify({password:$('#adminPassword').value})});msg.textContent='';load()}catch(err){msg.textContent=err.message}});$('#adminLogout')?.addEventListener('click',async()=>{await api('/api/admin/logout',{method:'POST'});location.reload()});load()}
  function setupYear(){ $$('.js-year').forEach(x=>x.textContent=new Date().getFullYear()); }
  document.addEventListener('DOMContentLoaded',()=>{setupHeader();setupModal();setupNewsletter();setupReveal();setupHome();setupPackagesPage();setupPackageDetail();setupContact();setupAdmin();setupYear();});
})();
