import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';

const __dirname=path.dirname(fileURLToPath(import.meta.url));
const ROOT=path.resolve(__dirname,'..');
const SB=process.env.SUPABASE_URL?.replace(/\/$/,'');
const SBKEY=process.env.SUPABASE_SERVICE_ROLE_KEY;
const ADMIN_PASSWORD=process.env.MYTRAVEL_ADMIN_PASSWORD||'';
const SESSION_SECRET=process.env.MYTRAVEL_SESSION_SECRET||'';
const WA=(process.env.MYTRAVEL_WHATSAPP||'919810958069').replace(/\D/g,'');
const statuses=new Set(['new','contacted','qualified','quoted','booked','closed']);
const clean=(v,n=300)=>String(v??'').replace(/[\u0000-\u001f\u007f]/g,' ').replace(/\s+/g,' ').trim().slice(0,n);
const emailOk=v=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v);
const phoneOk=v=>/^\+?[0-9][0-9\s()-]{7,19}$/.test(v);
const b64u=s=>Buffer.from(s).toString('base64url');
const sign=s=>crypto.createHmac('sha256',SESSION_SECRET).update(s).digest('base64url');
function makeSession(){const p=b64u(JSON.stringify({exp:Date.now()+8*60*60*1000}));return `${p}.${sign(p)}`}
function sessionOK(req){if(!SESSION_SECRET)return false;const c=(req.headers.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith('mt4s_admin='));if(!c)return false;const [p,s]=c.slice(11).split('.');if(!p||!s)return false;const x=sign(p);if(x.length!==s.length||!crypto.timingSafeEqual(Buffer.from(x),Buffer.from(s)))return false;try{return JSON.parse(Buffer.from(p,'base64url')).exp>Date.now()}catch{return false}}
async function sb(tableQuery,{method='GET',body,headers={}}={}){if(!SB||!SBKEY)throw new Error('SUPABASE_NOT_CONFIGURED');const r=await fetch(`${SB}/rest/v1/${tableQuery}`,{method,headers:{apikey:SBKEY,Authorization:`Bearer ${SBKEY}`,'Content-Type':'application/json',...headers},body:body===undefined?undefined:JSON.stringify(body)});const text=await r.text();if(!r.ok)throw new Error(text||`Supabase ${r.status}`);return text?JSON.parse(text):null}
function staticPackages(){return JSON.parse(fs.readFileSync(path.join(ROOT,'data','packages.json'),'utf8'))}
function filterPackages(list,q){const term=clean(q.destination||q.q||'',80).toLowerCase(),region=clean(q.region||'',30).toLowerCase(),type=clean(q.type||'',30).toLowerCase(),budget=clean(q.budget||'',50);let out=list.filter(p=>p.published!==false);if(term)out=out.filter(p=>[p.title,p.destination,p.region,p.country,p.summary,...(p.tags||[])].join(' ').toLowerCase().includes(term));if(region)out=out.filter(p=>String(p.region).toLowerCase()===region);if(type)out=out.filter(p=>String(p.type).toLowerCase()===type||(p.tags||[]).some(t=>String(t).toLowerCase()===type));if(budget&&budget!=='Any budget')out=out.filter(p=>{const n=Number(p.startingPrice);if(!n)return false;if(budget==='Under ₹50,000')return n<50000;if(budget==='₹50,000–₹1,00,000')return n>=50000&&n<=100000;if(budget==='₹1,00,000+')return n>100000;return true});return out}
function waUrl(l){const lines=['Hi MyTravel4Sure, I want to plan a trip.',`Name: ${l.name}`,`Phone: ${l.phone}`,`Destination: ${l.destination||'Open to suggestions'}`,`Travel month: ${l.travel_month||'Flexible'}`,`Travellers: ${l.travellers||'Not specified'}`,`Trip type: ${l.trip_type||'Holiday'}`,`Budget: ${l.budget||'Flexible'}`,`Reference: ${l.id}`];return `https://wa.me/${WA}?text=${encodeURIComponent(lines.join('\n'))}`}
function cookie(res,value,maxAge=28800){res.setHeader('Set-Cookie',`mt4s_admin=${value}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=${maxAge}`)}
export default async function handler(req,res){
  res.setHeader('Cache-Control','no-store'); res.setHeader('X-Content-Type-Options','nosniff');
  const raw=String(req.query.path||'').replace(/^\/+|\/+$/g,''); const parts=raw.split('/').filter(Boolean); const body=typeof req.body==='string'?(()=>{try{return JSON.parse(req.body)}catch{return {}}})():req.body||{};
  try{
    if(raw==='health'&&req.method==='GET')return res.status(200).json({ok:true,service:'mytravel4sure',persistence:SB&&SBKEY?'supabase':'static-read-only'});
    if(parts[0]==='packages'&&req.method==='GET'&&parts.length===1){let list;try{const rows=await sb('packages?select=payload,published&published=eq.true&order=updated_at.desc');list=(rows||[]).map(r=>({...r.payload,published:r.published}))}catch(e){if(e.message!=='SUPABASE_NOT_CONFIGURED')throw e;list=staticPackages()}return res.status(200).json({packages:filterPackages(list,req.query)})}
    if(parts[0]==='packages'&&req.method==='GET'&&parts[1]){const slug=clean(parts[1],100);let p=null;try{const rows=await sb(`packages?select=payload,published&slug=eq.${encodeURIComponent(slug)}&published=eq.true&limit=1`);p=rows?.[0]?.payload||null}catch(e){if(e.message!=='SUPABASE_NOT_CONFIGURED')throw e;p=staticPackages().find(x=>x.slug===slug&&x.published!==false)||null}return p?res.status(200).json({package:p}):res.status(404).json({error:'Package not found'})}
    if(raw==='enquiries'&&req.method==='POST'){if(clean(body.website,100))return res.status(200).json({ok:true});if(!SB||!SBKEY)return res.status(503).json({error:'Lead database is not configured on this deployment.'});const l={id:`MT4S-${Date.now().toString(36).toUpperCase()}-${crypto.randomBytes(2).toString('hex').toUpperCase()}`,created_at:new Date().toISOString(),updated_at:new Date().toISOString(),status:'new',name:clean(body.name,100),phone:clean(body.phone,30),email:clean(body.email,160)||null,destination:clean(body.destination,100),travel_month:clean(body.month||body.travel_month,50),travellers:clean(body.travellers,30),trip_type:clean(body.tripType||body.trip_type,60),budget:clean(body.budget,60),notes:clean(body.notes,1200),source:clean(body.source||'website',80)};if(!l.name||!phoneOk(l.phone)||(l.email&&!emailOk(l.email)))return res.status(422).json({error:'Please enter a valid name, phone and email.'});await sb('leads',{method:'POST',body:l,headers:{Prefer:'return=minimal'}});return res.status(201).json({ok:true,leadId:l.id,whatsappUrl:waUrl(l)})}
    if(raw==='newsletter'&&req.method==='POST'){if(clean(body.website,100))return res.status(200).json({ok:true});if(!SB||!SBKEY)return res.status(503).json({error:'Newsletter database is not configured on this deployment.'});const e=clean(body.email,160).toLowerCase();if(!emailOk(e))return res.status(422).json({error:'Enter a valid email address.'});await sb('newsletter?on_conflict=email',{method:'POST',body:{email:e,created_at:new Date().toISOString(),source:clean(body.source||'footer',50)},headers:{Prefer:'resolution=merge-duplicates,return=minimal'}});return res.status(201).json({ok:true})}
    if(raw==='admin/login'&&req.method==='POST'){if(!ADMIN_PASSWORD||!SESSION_SECRET)return res.status(503).json({error:'Admin authentication is not configured.'});const a=Buffer.from(String(body.password||'')),b=Buffer.from(ADMIN_PASSWORD);if(a.length!==b.length||!crypto.timingSafeEqual(a,b))return res.status(401).json({error:'Invalid password.'});cookie(res,makeSession());return res.status(200).json({ok:true})}
    if(raw==='admin/logout'&&req.method==='POST'){cookie(res,'',0);return res.status(200).json({ok:true})}
    if(parts[0]==='admin'){if(!sessionOK(req))return res.status(401).json({error:'Authentication required.'});if(!SB||!SBKEY)return res.status(503).json({error:'Supabase is required for the Vercel admin dashboard.'});
      if(raw==='admin/leads'&&req.method==='GET'){const rows=await sb('leads?select=id,created_at,updated_at,status,name,phone,email,destination,travel_month,travellers,trip_type,budget,notes,source&order=created_at.desc&limit=500');return res.status(200).json({leads:rows||[]})}
      if(raw==='admin/newsletter'&&req.method==='GET'){const rows=await sb('newsletter?select=email,created_at,source&order=created_at.desc&limit=1000');return res.status(200).json({subscribers:rows||[]})}
      if(raw==='admin/packages'&&req.method==='GET'){const rows=await sb('packages?select=payload,published&order=updated_at.desc');return res.status(200).json({packages:(rows||[]).map(r=>({...r.payload,published:r.published}))})}
      if(parts[1]==='leads'&&parts[2]&&req.method==='PATCH'){const st=clean(body.status,20);if(!statuses.has(st))return res.status(422).json({error:'Invalid status'});await sb(`leads?id=eq.${encodeURIComponent(parts[2])}`,{method:'PATCH',body:{status:st,updated_at:new Date().toISOString()},headers:{Prefer:'return=minimal'}});return res.status(200).json({ok:true})}
      if(parts[1]==='packages'&&parts[2]&&req.method==='PATCH'){const slug=clean(parts[2],100);const rows=await sb(`packages?select=payload,published&slug=eq.${encodeURIComponent(slug)}&limit=1`);if(!rows?.[0])return res.status(404).json({error:'Package not found'});const old=rows[0].payload;const allowed=['title','destination','region','country','type','nights','days','startingPrice','priceStatus','featured','image','summary','availability','tags','highlights','inclusions','itinerary'];for(const k of allowed)if(k in body)old[k]=body[k];const published='published'in body?!!body.published:!!rows[0].published;await sb(`packages?slug=eq.${encodeURIComponent(slug)}`,{method:'PATCH',body:{payload:{...old,published},published,updated_at:new Date().toISOString()},headers:{Prefer:'return=minimal'}});return res.status(200).json({ok:true,package:{...old,published}})}
    }
    return res.status(404).json({error:'API route not found'});
  }catch(err){console.error(err);return res.status(500).json({error:'Server error'})}
}
